POE2_SITE_UI.craft={
 // 旧版输入框的提示文字；由 sites.js 限制为明确的 init 状态。
 'Search for a base or item':'搜尋基底或物品','Search for an affix':'搜尋詞綴',
 // 词缀筛选标签的语义与施法者职业名分开处理。
 'Caster':'法術','Critical':'暴擊','Resistance':'抗性','Attribute':'能力值','Tag filter':'標籤篩選',
 // 制作器固定控件与状态；不使用单词 Hit/And 的全站替换修补快捷键说明。
 'Base group':'基底分類','Choose a base':'選擇基底','Choose a crafting method':'選擇製作方式','Close filters':'關閉篩選','Close all groups':'收起所有群組','Choose an item class':'選擇物品類別','Selected item base':'已選物品基底','Search modifiers for this base':'搜尋此基底的詞綴','Currencies':'通貨','Socketables':'可鑲嵌物品','Generate':'產生','Group type':'群組類型','Matches':'符合','Requirement':'條件','Add a requirement group':'新增條件群組','Simulate this outcome':'模擬此結果','Calculations':'計算結果','Create simulation':'建立模擬','Evaluating setup validity':'正在檢查設定是否有效','No crafting method selected':'尚未選擇製作方式','Modifier types':'詞綴類型','Explicits':'外延詞綴','Corrupted Implicits':'汙染固定詞綴','Base':'基底','Tiers':'階級','Type %':'類型比例','Weight %':'權重比例','Totals':'總計','New Item':'新物品','Requires level':'需求等級','Int':'智慧','Connect with Patreon':'連結 Patreon','Donations':'贊助','Change language':'切換語言','Ad space':'廣告位置',
 // 主站与 beta 站共用制作界面标签，不改写物品数值或导入内容。
 'Choose an item group':'選擇物品分類','Offhand':'副手裝備','Two-Handed Weapon':'雙手武器','Search for a craftable item':'搜尋可製作的物品','Import an item':'匯入物品','*NEW*':'新功能',
 // beta 首页的完整功能说明按原句配对，保留内嵌控件和快捷键说明。
 'Emulate directly in the crafting interface':'直接在製作介面中模擬','Apply the selected crafting method by hovering over the item and clicking on it.':'將游標移到物品上並點擊，即可套用選定的製作方式。','Build complex calculator requirements':'設定複雜的計算條件','Set up requirement groups with partial or complete matching, query for open affixes and more.':'設定部分或全部符合的條件群組，查詢空餘詞綴位置等。','Simulate entire crafting processes for a project':'模擬專案的完整製作流程','Create crafting steps and use routing and conditions to simulate a crafting strategy.':'建立製作步驟，透過流程分支與條件模擬製作策略。','Save items to inventory':'將物品儲存至物品庫','Store items for future reference, create and manage storage tabs and more.':'儲存物品以供日後參考，並建立及管理儲存分頁。','Expansive user settings':'豐富的使用者設定','Tailor the UI to your liking, set up custom pricing and toggle user options.':'依喜好調整介面、自訂價格，並切換使用者選項。','And much more...':'還有更多功能…','Expanded data viewability':'更完整的資料檢視','Browse compiled data, compare patches, view items and modifier details and more.':'瀏覽整理好的資料、比較版本，並查看物品與詞綴詳情。',
 'Current patch':'目前版本','Early-Access':'搶先體驗','ILvl':'物品等級','Choose base group':'選擇基底分類','Offhands':'副手裝備','One-Handed Weapons':'單手武器','Two-Handed Weapons':'雙手武器','Tablets':'碑牌','Website rework':'網站改版','new site version':'新版網站',"what's new":'最新動態','Roadmap':'開發規劃','Compare':'比較','Crafting':'製作','Data':'資料','Inventory':'物品庫','Languages':'語言','Key Features':'主要功能','Usage':'使用方式','Instructions':'操作說明','Customizability':'自訂功能','Learn how to craft':'學習製作','Disclaimer':'免責聲明','Privacy':'隱私','Donate':'贊助','Developers':'開發者',
 'Calculator':'計算器','Simulator':'模擬器','Emulator':'製作模擬','How to use':'使用方法','Weightings':'權重','Changelog':'更新紀錄','Import item':'匯入物品','Export item':'匯出物品','RAW Export':'匯出原始資料','Advanced':'進階','Annul bad mod':'移除不需要的詞綴','Fractured':'破裂','Special rules':'特殊規則','Open filters':'開啟篩選','Open all groups':'展開所有群組','Share link':'分享連結','Latest Changes':'最新變更','Item level':'物品等級','Item Level':'物品等級','Base item':'物品基底','Select a base':'選擇基底','Prefixes':'前綴','Suffixes':'後綴','Prefix':'前綴','Suffix':'後綴','Weight':'權重','Weighting':'權重','Tier':'階級','Chance':'機率','Cost':'成本','Average cost':'平均成本','Attempts':'嘗試次數','Success chance':'成功機率','Confidence':'可信度','Craft':'製作','Crafting method':'製作方式','Add modifier':'新增詞綴','Remove modifier':'移除詞綴','Required':'必要','Present':'已存在','Start':'開始','Stop':'停止','Undo':'復原','Redo':'重做','There are no bases or items matching this search term.':'沒有符合搜尋條件的基底或物品。','There are no affixes matching this search term.':'沒有符合搜尋條件的詞綴。'
};
// 实页 #instructions 内的文案片段，保留中间鼠标图片、快捷键及强调节点。
globalThis.POE2_CRAFT_INSTRUCTIONS={
 'Instructions':'操作說明','Hover':'將游標移','over an item and':'到物品上，並按','to':'以','apply':'套用','the currently selected crafting method to it.':'目前選擇的製作方式。',
 'Hold':'按住','to toggle between':'以切換','advanced':'進階','and':'與','classic':'一般','modifier descriptions for items.':'物品詞綴說明。',
 'to force':'可讓','tooltips':'物品提示','to stay visible and enable the ability to drill-down.':'保持顯示，並查看更詳細的內容。',
 'Hit':'按下','revert':'復原','emulator actions.':'製作模擬操作。','Left':'按左鍵','add':'新增','or':'或','remove':'移除','modifiers from the modpool to the current item.':'目前物品的詞綴（從詞綴池選取）。',
 'Right':'按右鍵','to access the context menu':'即可查看該元素的選單','options':'選項','for elements.':'。'
};
