const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const registry=require('../extension/modules.js');
assert.equal(registry.match('https://maxroll.gg/d4'),null);
assert.equal(registry.match('https://mobalytics.gg/lol'),null);
assert.equal(registry.match('https://poe.ninja/poe1/builds'),null);
assert.equal(registry.match('https://www.pathofexile.com/trade2/search/poe2'),'trade');
assert.equal(registry.match('https://www.pathofexile.com/forum'),'official');
assert.equal(registry.match('https://maxroll.gg.evil.test/poe2'),null);
assert.deepEqual(registry.settings({enabled:false,bilingual:true},'trade'),{enabled:false,bilingual:true});
assert.equal(registry.settings({enabled:false},'ninja').enabled,true);
(async()=>{
 const ext=path.resolve('extension'),profile=fs.mkdtempSync(path.resolve('tests/sites-profile-'));
 const context=await chromium.launchPersistentContext(profile,{channel:'msedge',headless:true,args:['--disable-extensions-except='+ext,'--load-extension='+ext]});
 try{
  const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
  const html=label=>`<!doctype html><html><head></head><body><h1>${label}</h1><div id="item">Exalted Orb</div><div id="dynamic">+100 to maximum Life</div><input value="Search" placeholder="Search"><select><option>Search</option></select><div class="accountName">Search</div><div contenteditable="true">Search</div><pre>Search</pre><div class="postContent">Search</div><a id="link" href="/original?q=Search">Home</a><button title="Search" aria-label="Search">Search</button></body></html>`;
  await context.route(/^https:\/\//,r=>r.fulfill({contentType:'text/html',body:html(new URL(r.request().url()).searchParams.get('label')||'Search')}));
  const page=await context.newPage(),cdp=await context.newCDPSession(page);let extensionId;
  cdp.on('Runtime.executionContextCreated',async({context:ctx})=>{if(!ctx.auxData?.isDefault){try{const r=await cdp.send('Runtime.evaluate',{expression:'chrome.runtime.id',contextId:ctx.id,returnByValue:true});if(r.result.value)extensionId=r.result.value}catch{}}});
  await cdp.send('Runtime.enable');
  await page.goto('https://poe.ninja/poe2/builds?label=Economy');
  await page.waitForFunction(()=>document.querySelector('h1').textContent==='經濟');
  assert(extensionId,'Extension isolated context must expose its id');
  const popup=await context.newPage();await popup.goto(`chrome-extension://${extensionId}/popup.html`);
  await popup.waitForSelector('#official-enabled');assert.equal(await popup.locator('.module').count(),7);
  const set=async(id,enabled,bilingual=false)=>popup.evaluate(({id,enabled,bilingual})=>chrome.storage.local.set({['module.'+id]:{enabled,bilingual}}),{id,enabled,bilingual});
  const cases=[['ninja','https://poe.ninja/poe2/builds','Economy','經濟'],['pobb','https://pobb.in/example','Share your Build','分享你的構築'],['maxroll','https://maxroll.gg/poe2','Build Guides','流派指南'],['mobalytics','https://mobalytics.gg/poe-2','Starter Builds','開荒流派'],['craft','https://www.craftofexile.com/','Calculator','計算器'],['official','https://www.pathofexile.com/','Patch Notes','更新公告']];
  for(const [id,url,label,zh]of cases){
   await page.goto(url+'?label='+encodeURIComponent(label));await page.waitForFunction(zh=>document.querySelector('h1').textContent===zh,zh);
   assert.equal(await page.locator('#item').innerText(),'崇高石');assert.equal(await page.locator('input').inputValue(),'Search');assert.equal(await page.locator('select').inputValue(),'Search');
   for(const sel of ['.accountName','[contenteditable]','pre','.postContent'])assert.equal(await page.locator(sel).innerText(),'Search');
   assert.equal(await page.locator('#link').getAttribute('href'),'/original?q=Search');
   assert.equal(await page.locator('input').getAttribute('placeholder'),'搜尋');
   await page.locator('#dynamic').evaluate(el=>el.textContent='+250 to maximum Life');await page.waitForFunction(()=>document.querySelector('#dynamic').textContent.includes('250最大生命'));
   await set(id,false);await page.waitForFunction(label=>document.querySelector('h1').textContent===label,label);assert.equal(await page.locator('#dynamic').innerText(),'+250 to maximum Life');assert.equal(await page.locator('input').getAttribute('placeholder'),'Search');
   await set(id,true,true);await page.waitForFunction(label=>document.querySelector('h1').textContent.includes('('+label+')'),label);
   await page.reload();await page.waitForFunction(label=>document.querySelector('h1').textContent.includes('('+label+')'),label);
   await set(id,true);await page.waitForFunction(zh=>document.querySelector('h1').textContent===zh,zh);
  }
  await page.goto('https://mobalytics.gg/poe-2/builds/example');
  await page.evaluate(()=>{
   const tip=document.createElement('div');tip.id='moba-tip';tip.innerHTML='<p id="requires">Requires: <span id="required-level">1</span> Level.</p><ul><li><span id="moba-life">+<span id="life-range">(10-19)</span> to maximum <span>Life</span></span><span class="tier">P13</span></li><li><span id="moba-fire">+(6-10)% to Fire Resistance</span><span class="tier">S8</span></li><li><span id="moba-cold">+<span>(6-10)</span>% to <span>Cold Resistance</span></span><span class="tier">S8</span></li></ul><button id="track">Track Build</button>';document.body.append(tip);window.mobaOriginal=tip.innerHTML;
  });
  await page.waitForFunction(()=>document.querySelector('#requires').textContent==='需求：等級 1');
  assert.match(await page.locator('#moba-life').innerText(),/\+\(10-19\).*最大生命/);
  assert.match(await page.locator('#moba-fire').innerText(),/\+\(6-10\)%.*火焰抗性/);
  assert.match(await page.locator('#moba-cold').innerText(),/\+\(6-10\)%.*冰冷抗性/);
  assert.deepEqual(await page.locator('.tier').allTextContents(),['P13','S8','S8']);assert.equal(await page.locator('#track').innerText(),'追蹤流派');
  await set('mobalytics',false);await page.waitForFunction(()=>document.querySelector('#moba-tip').innerHTML===window.mobaOriginal);
  await set('mobalytics',true,true);await page.waitForFunction(()=>document.querySelector('#moba-life').textContent.includes('(+(10-19) to maximum Life)'));
  await page.locator('#required-level').evaluate(el=>el.firstChild.nodeValue='20');await page.waitForFunction(()=>document.querySelector('#requires').textContent==='需求：等級 20 (Requires: 20 Level.)');
  await set('mobalytics',true);await page.waitForFunction(()=>document.querySelector('#requires').textContent==='需求：等級 20');
  await page.goto('https://poe.ninja/poe2/builds');
  await page.evaluate(()=>{
   const labels=document.createElement('div');labels.innerHTML='<h2 id="spirit">SPIRIT SKILLS</h2><p id="rare">Rare Belt</p><p id="weapons">Bow / Quiver</p><select id="typed"><option value="original-charm">Charm</option></select>';document.body.append(labels);
   const tooltip=document.createElement('div');tooltip.id='tooltip';tooltip.setAttribute('role','tooltip');
   tooltip.innerHTML='<div id="used">Used when you become <span>Ignited</span></div><div id="charge"><span id="range">(20-25)</span>% Chance to gain a <span>Charge</span> when you kill an enemy</div><div id="ground">Creates <span>Ignited Ground</span> for 4 seconds when used, <span>Igniting</span> enemies as though dealing <span>Fire</span> damage equal to <span id="damage">500</span>% of your maximum <span>Life</span></div>';
   document.body.append(tooltip);window.originalTooltip=tooltip.innerHTML;window.rangeNode=document.querySelector('#range');
  });
  await page.waitForFunction(()=>document.querySelector('#used').textContent==='當你被點燃時使用');
  assert.equal(await page.locator('#spirit').innerText(),'精魂技能');assert.equal(await page.locator('#rare').innerText(),'稀有腰帶');assert.equal(await page.locator('#weapons').innerText(),'弓／箭袋');assert.equal(await page.locator('#typed option').innerText(),'護符');assert.equal(await page.locator('#typed').inputValue(),'original-charm');
  assert.equal(await page.locator('#charge').innerText(),'殺死敵人時有(20-25)%機率獲得一顆充能');
  assert.equal(await page.locator('#ground').innerText(),'使用時生成持續4秒的點燃地面來點燃敵人，造成等同於你最大生命500%的火焰傷害');
  await set('ninja',false);await page.waitForFunction(()=>document.querySelector('#tooltip').innerHTML===window.originalTooltip);
  assert(await page.evaluate(()=>document.querySelector('#range')===window.rangeNode),'Preserve framework-owned spans');
  await set('ninja',true);await page.waitForFunction(()=>document.querySelector('#used').textContent==='當你被點燃時使用');
  await page.locator('#damage').evaluate(el=>el.firstChild.nodeValue='650');await page.waitForFunction(()=>document.querySelector('#ground').textContent.includes('650%'));
  await set('ninja',true,true);await page.waitForFunction(()=>document.querySelector('#ground').textContent.includes('(Creates Ignited Ground'));
  assert(!await page.locator('#ground').innerText().then(text=>text.includes('Creates 點燃地面')),'No mixed-language original');
  await set('ninja',false);await page.waitForFunction(()=>document.querySelector('#ground').textContent.includes('equal to 650%'));
  await set('ninja',true);
  await page.goto('https://maxroll.gg/poe2?label=Build%20Guides');await page.waitForFunction(()=>document.querySelector('h1').textContent==='流派指南');
  await set('ninja',false);assert.equal(await page.locator('h1').innerText(),'流派指南');
  await page.evaluate(()=>history.pushState({},'','/d4'));await page.waitForFunction(()=>document.querySelector('h1').textContent==='Build Guides');
  await page.evaluate(()=>history.pushState({},'','/poe2'));await page.waitForFunction(()=>document.querySelector('h1').textContent==='流派指南');
  await page.goto('https://www.pathofexile.com/trade2/search/poe2/');await page.waitForFunction(()=>document.querySelector('h1').textContent==='搜尋');
  await set('official',false);assert.equal(await page.locator('h1').innerText(),'搜尋');
  await set('trade',false);await page.waitForFunction(()=>document.querySelector('h1').textContent==='Search');
  await set('official',true);assert.equal(await page.locator('h1').innerText(),'Search');
  await set('trade',true);await page.waitForFunction(()=>document.querySelector('h1').textContent==='搜尋');
  await popup.reload();await popup.waitForSelector('#ninja-enabled');assert.equal(await popup.locator('#ninja-enabled').isChecked(),false);assert.equal(await popup.locator('#maxroll-enabled').isChecked(),true);
  await popup.locator('#ninja-enabled').check();assert.equal((await popup.evaluate(()=>chrome.storage.local.get('module.ninja')))['module.ninja'].enabled,true);
  await popup.setViewportSize({width:560,height:600});await popup.screenshot({path:'tests/modules-popup.png',fullPage:true});assert(await popup.evaluate(()=>document.body.scrollHeight<=600),'Popup fits browser height limit');
  assert(await popup.evaluate(()=>{const grid=document.querySelector('#modules');return grid.scrollHeight===grid.clientHeight&&document.documentElement.scrollWidth<=560}),'All cards fit without nested or horizontal scrolling');assert.deepEqual(errors,[]);
  console.log('PASS: six actual MV3 site modules, 7 popup controls, live restore, bilingual persistence, dynamic values, protected fields, SPA routing, trade/official isolation');
 }finally{await context.close();const resolved=path.resolve(profile);assert.equal(path.dirname(resolved),path.resolve('tests'));assert(path.basename(resolved).startsWith('sites-profile-'));fs.rmSync(resolved,{recursive:true,force:true})}
})().catch(e=>{console.error(e);process.exitCode=1});
